/*
THIS IS A GENERATED BUNDLE FOR OBSIDIAN PLUGIN.
DO NOT EDIT THIS FILE DIRECTLY.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NextcloudSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  serverUrl: "",
  username: "",
  appPassword: "",
  remoteBasePath: "",
  largeFileThresholdMb: 10,
  chunkSizeMb: 5,
  autoSyncIntervalMinutes: 0,
  syncOnStartup: false,
  syncOnChange: false,
  syncOnChangeDebounceMs: 1500,
  deleteStrategy: "trash",
  conflictStrategy: "keep-both",
  excludePatterns: "",
  logRetentionDays: 30
};
var NextcloudSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u670D\u52A1\u5668\u5730\u5740").setDesc("Nextcloud \u5730\u5740\uFF0C\u4F8B\u5982 https://cloud.example.com\uFF08\u5F3A\u70C8\u5EFA\u8BAE HTTPS\uFF09").addText(
      (text) => text.setPlaceholder("https://cloud.example.com").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
        this.plugin.settings.serverUrl = value.trim().replace(/\/+$/, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u7528\u6237\u540D").setDesc("Nextcloud \u767B\u5F55\u7528\u6237\u540D").addText(
      (text) => text.setPlaceholder("username").setValue(this.plugin.settings.username).onChange(async (value) => {
        this.plugin.settings.username = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("App \u5BC6\u7801").setDesc("\u5728 Nextcloud\u300C\u5B89\u5168\u300D\u9875\u751F\u6210\u7684\u5E94\u7528\u5BC6\u7801\uFF08\u5EFA\u8BAE\u7528\u5E94\u7528\u5BC6\u7801\u800C\u975E\u4E3B\u5BC6\u7801\uFF09").addText(
      (text) => text.setPlaceholder("app-password").setValue(this.plugin.settings.appPassword).onChange(async (value) => {
        this.plugin.settings.appPassword = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8FDC\u7AEF\u6839\u76EE\u5F55").setDesc("vault \u5728\u8FDC\u7AEF\u5B58\u653E\u7684\u76EE\u5F55\u540D\uFF0C\u7559\u7A7A\u5219\u4F7F\u7528 vault \u540D").addText(
      (text) => text.setPlaceholder("Obsidian").setValue(this.plugin.settings.remoteBasePath).onChange(async (value) => {
        this.plugin.settings.remoteBasePath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").setDesc("\u9A8C\u8BC1\u5730\u5740\u3001\u7528\u6237\u540D\u4E0E\u5BC6\u7801\u662F\u5426\u6B63\u786E").addButton(
      (btn) => btn.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5").onClick(async () => {
        btn.setDisabled(true).setButtonText("\u6D4B\u8BD5\u4E2D\u2026");
        try {
          const ok = await this.plugin.testConnection();
          if (ok) {
            btn.setButtonText("\u2705 \u8FDE\u63A5\u6210\u529F");
          } else {
            btn.setButtonText("\u274C \u8FDE\u63A5\u5931\u8D25");
          }
        } catch {
          btn.setButtonText("\u274C \u8FDE\u63A5\u5931\u8D25");
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5927\u6587\u4EF6\u9608\u503C\uFF08MB\uFF09").setDesc("\u8D85\u8FC7\u6B64\u5927\u5C0F\u7684\u6587\u4EF6\u4F7F\u7528 chunking v2 \u5206\u5757\u4E0A\u4F20").addText(
      (text) => text.setValue(String(this.plugin.settings.largeFileThresholdMb)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.largeFileThresholdMb = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5206\u5757\u5927\u5C0F\uFF08MB\uFF09").setDesc("chunking v2 \u6BCF\u5757\u5927\u5C0F\uFF0C\u9ED8\u8BA4 5MB").addText(
      (text) => text.setValue(String(this.plugin.settings.chunkSizeMb)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.chunkSizeMb = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5B9A\u65F6\u540C\u6B65\uFF08\u5206\u949F\uFF09").setDesc("0 = \u5173\u95ED").addText(
      (text) => text.setValue(String(this.plugin.settings.autoSyncIntervalMinutes)).onChange(async (value) => {
        const n = parseInt(value, 10);
        this.plugin.settings.autoSyncIntervalMinutes = isNaN(n) ? 0 : n;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u542F\u52A8\u65F6\u540C\u6B65").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (value) => {
        this.plugin.settings.syncOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6587\u4EF6\u53D8\u66F4\u81EA\u52A8\u540C\u6B65").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnChange).onChange(async (value) => {
        this.plugin.settings.syncOnChange = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5220\u9664\u7B56\u7565").setDesc("trash\uFF1A\u5220\u9664\u8D70\u56DE\u6536\u7AD9\u515C\u5E95\uFF08\u63A8\u8350\uFF09\uFF1Bnever\uFF1A\u53EA\u589E\u4E0D\u5220").addDropdown(
      (dd) => dd.addOption("trash", "\u56DE\u6536\u7AD9\u515C\u5E95").addOption("never", "\u53EA\u589E\u4E0D\u5220").setValue(this.plugin.settings.deleteStrategy).onChange(async (value) => {
        this.plugin.settings.deleteStrategy = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u51B2\u7A81\u7B56\u7565").addDropdown(
      (dd) => dd.addOption("keep-both", "\u4FDD\u7559\u53CC\u65B9").addOption("local-wins", "\u672C\u5730\u8986\u76D6").addOption("remote-wins", "\u8FDC\u7AEF\u8986\u76D6").setValue(this.plugin.settings.conflictStrategy).onChange(async (value) => {
        this.plugin.settings.conflictStrategy = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5FFD\u7565\u89C4\u5219").setDesc("\u6BCF\u884C\u4E00\u4E2A glob\uFF0C\u4F8B\u5982 temp/\u3001*.log").addTextArea(
      (ta) => ta.setPlaceholder("temp/\n*.log").setValue(this.plugin.settings.excludePatterns).onChange(async (value) => {
        this.plugin.settings.excludePatterns = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u65E5\u5FD7\u4FDD\u7559\u5929\u6570").addText(
      (text) => text.setValue(String(this.plugin.settings.logRetentionDays)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.logRetentionDays = n;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/webdav/client.ts
var import_obsidian2 = require("obsidian");

// src/webdav/xmlParser.ts
function childrenByLocalName(el, localName) {
  const out = [];
  for (let i = 0; i < el.children.length; i++) {
    const c = el.children[i];
    if (c.localName === localName)
      out.push(c);
  }
  return out;
}
function firstByLocalName(el, localName) {
  for (let i = 0; i < el.children.length; i++) {
    const c = el.children[i];
    if (c.localName === localName)
      return c;
  }
  return null;
}
function relativePathFromHref(href, baseHref) {
  let h = href;
  try {
    h = decodeURIComponent(h);
  } catch {
  }
  h = h.replace(/^\/+/, "");
  let b = baseHref;
  try {
    b = decodeURIComponent(b);
  } catch {
  }
  b = b.replace(/^\/+/, "").replace(/\/+$/, "");
  if (b && h.startsWith(b + "/")) {
    h = h.slice(b.length + 1);
  } else if (h === b) {
    h = "";
  }
  return h.replace(/\/+$/, "");
}
function parsePropfind(xml, baseHref) {
  let doc;
  try {
    doc = new DOMParser().parseFromString(xml, "application/xml");
  } catch {
    return [];
  }
  if (doc.getElementsByTagName("parsererror").length > 0) {
    return [];
  }
  const responses = doc.getElementsByTagNameNS("*", "response");
  const entries = [];
  for (const resp of Array.from(responses)) {
    const hrefEl = firstByLocalName(resp, "href");
    if (!hrefEl || !hrefEl.textContent)
      continue;
    const href = hrefEl.textContent;
    const propstats = childrenByLocalName(resp, "propstat");
    let prop = null;
    for (const ps of propstats) {
      const statusEl = firstByLocalName(ps, "status");
      if (statusEl && statusEl.textContent && statusEl.textContent.includes("200")) {
        prop = firstByLocalName(ps, "prop");
        break;
      }
    }
    if (!prop)
      continue;
    const etagEl = firstByLocalName(prop, "getetag");
    const mtimeEl = firstByLocalName(prop, "getlastmodified");
    const lenEl = firstByLocalName(prop, "getcontentlength");
    const typeEl = firstByLocalName(prop, "getcontenttype");
    const resTypeEl = firstByLocalName(prop, "resourcetype");
    const isDir = resTypeEl !== null && firstByLocalName(resTypeEl, "collection") !== null;
    const checksums = [];
    const checksumContainers = prop.getElementsByTagNameNS("*", "checksums");
    for (const container of Array.from(checksumContainers)) {
      const childChecksums = container.getElementsByTagNameNS("*", "checksum");
      if (childChecksums.length > 0) {
        for (const cs of Array.from(childChecksums)) {
          const t = cs.textContent?.trim();
          if (t)
            checksums.push(...t.split(/\s+/).filter(Boolean));
        }
      } else {
        const t = container.textContent?.trim();
        if (t)
          checksums.push(...t.split(/\s+/).filter(Boolean));
      }
    }
    let sha1;
    for (const c of checksums) {
      if (c.toUpperCase().startsWith("SHA1:")) {
        sha1 = c.slice(5);
        break;
      }
    }
    const sizeRaw = lenEl?.textContent;
    entries.push({
      path: relativePathFromHref(href, baseHref),
      href,
      isDir,
      etag: etagEl?.textContent?.trim() || void 0,
      lastModified: mtimeEl?.textContent?.trim() || void 0,
      size: sizeRaw ? parseInt(sizeRaw, 10) : void 0,
      contentType: typeEl?.textContent?.trim() || void 0,
      checksums,
      sha1
    });
  }
  return entries.filter((e) => !(e.isDir && e.path === ""));
}

// src/webdav/chunkedUpload.ts
async function uploadWithChunking(client, relPath, data, chunkSize) {
  const destUrl = client.uploadChunkUrl(relPath, false);
  const basename = relPath.split("/").pop() || "file";
  const transferId = encodeURIComponent(basename);
  const uploadUrl = (suffix) => client.uploadChunkUrl(`${transferId}/${suffix}`, true);
  const mk = await client.rawRequest("MKCOL", uploadUrl(""), {
    headers: { Destination: destUrl }
  });
  if (mk.status !== 201 && mk.status !== 405) {
    throw new Error(`chunked MKCOL failed: HTTP ${mk.status}`);
  }
  const total = data.byteLength;
  const nChunks = Math.max(1, Math.ceil(total / chunkSize));
  for (let i = 0; i < nChunks; i++) {
    const start = i * chunkSize;
    const end = Math.min(total, start + chunkSize);
    const chunk = data.slice(start, end);
    const chunkName = `${i + 1}`.padStart(5, "0");
    const r = await client.rawRequest("PUT", uploadUrl(chunkName), {
      body: chunk,
      contentType: "application/octet-stream",
      headers: {
        Destination: destUrl,
        "OC-Total-Length": `${total}`
      }
    });
    if (r.status < 200 || r.status >= 300) {
      await client.rawRequest("DELETE", uploadUrl(""));
      throw new Error(`chunked PUT ${chunkName} failed: HTTP ${r.status}`);
    }
  }
  const mv = await client.rawRequest("MOVE", uploadUrl(".file"), {
    headers: {
      Destination: destUrl,
      "OC-Total-Length": `${total}`,
      Overwrite: "T"
    }
  });
  if (mv.status < 200 || mv.status >= 300) {
    await client.rawRequest("DELETE", uploadUrl(""));
    throw new Error(`chunked MOVE failed: HTTP ${mv.status}`);
  }
}

// src/webdav/client.ts
var WebdavClient = class {
  constructor(settings) {
    this.capsCache = null;
    this.settings = settings;
  }
  /** 服务器地址规范化（去尾斜杠） */
  get server() {
    return this.settings.serverUrl.replace(/\/+$/, "");
  }
  /** 文件 WebDAV 根 Base URL */
  get filesBase() {
    const user = encodeURIComponent(this.settings.username);
    let base = this.settings.remoteBasePath.trim().replace(/^\/+|\/+$/g, "");
    const tail = base ? `/${encodeURIComponent(base)}` : "";
    return `${this.server}/remote.php/dav/files/${user}${tail}/`;
  }
  /** 上传地址：dav/files → dav/uploads */
  get uploadsBase() {
    const user = encodeURIComponent(this.settings.username);
    return `${this.server}/remote.php/dav/uploads/${user}`;
  }
  /** Basic 认证头 */
  get authHeader() {
    const cred = `${this.settings.username}:${this.settings.appPassword}`;
    let b64;
    try {
      b64 = btoa(unescape(encodeURIComponent(cred)));
    } catch {
      b64 = btoa(cred);
    }
    return `Basic ${b64}`;
  }
  /** 路径段编码（保留斜杠分隔） */
  enc(p) {
    return p.split("/").map((s) => encodeURIComponent(s)).join("/");
  }
  /** 完整 URL（可选仅编码路径部分） */
  url(relPath, forUpload = false) {
    const base = forUpload ? this.uploadsBase : this.filesBase;
    if (!relPath)
      return base;
    const clean = relPath.replace(/^\/+/, "");
    return base + this.enc(clean);
  }
  /** 归一化请求封装 */
  async request(method, url, opts = {}) {
    const headers = {
      Authorization: this.authHeader,
      "Cache-Control": "no-cache",
      ...opts.headers
    };
    const param = {
      url,
      method,
      headers,
      throw: false
    };
    if (opts.body !== void 0) {
      param.body = opts.body;
      if (opts.contentType)
        param.contentType = opts.contentType;
    }
    const resp = await (0, import_obsidian2.requestUrl)(param);
    if (opts.throwOnError && resp.status >= 400) {
      throw new Error(`WebDAV ${method} ${url} failed: HTTP ${resp.status}`);
    }
    return {
      status: resp.status,
      headers: resp.headers,
      body: resp.arrayBuffer,
      text: resp.text
    };
  }
  /** 测试连接：对根目录 depth=0 PROPFIND */
  async testConnection() {
    const r = await this.request("PROPFIND", this.filesBase, {
      headers: { Depth: "0" }
    });
    return r.status >= 200 && r.status < 300;
  }
  /** 探测服务器能力（chunking v2 / 是否 Nextcloud），带缓存 */
  async getCapabilities() {
    if (this.capsCache)
      return this.capsCache;
    const capsUrl = `${this.server}/ocs/v1.php/cloud/capabilities?format=json`;
    try {
      const r = await this.request("GET", capsUrl, {
        headers: { "OCS-APIRequest": "true", Accept: "application/json" }
      });
      if (r.status >= 200 && r.status < 300) {
        const json = JSON.parse(r.text || "{}");
        const dav = json?.ocs?.data?.capabilities?.dav || {};
        const isNextcloud = !!json?.ocs?.data?.version?.edition || !!dav?.chunking;
        return {
          chunkingV2: isNextcloud && dav?.chunking !== void 0,
          isNextcloud,
          version: json?.ocs?.data?.version?.string
        };
      }
    } catch {
    }
    return { chunkingV2: false, isNextcloud: false };
  }
  /** 带缓存的能力读取（上传时复用，避免每文件一次网络探测） */
  async getCapsCached() {
    if (!this.capsCache)
      this.capsCache = await this.getCapabilities();
    return this.capsCache;
  }
  /** 递归列出远端所有条目（逐层 BFS，避免 depth=infinity 超时） */
  async listAll() {
    const out = [];
    const queue = [""];
    while (queue.length) {
      const dir = queue.shift();
      const r = await this.request("PROPFIND", this.url(dir), {
        headers: { Depth: "1" }
      });
      if (r.status < 200 || r.status >= 300)
        continue;
      const baseHref = this.url(dir);
      const entries = parsePropfind(r.text, baseHref);
      for (const e of entries) {
        if (e.isDir && e.path !== dir) {
          queue.push(e.path);
        }
        out.push(e);
      }
    }
    return out;
  }
  /** 下载文件 → ArrayBuffer */
  async getFile(relPath) {
    const r = await this.request("GET", this.url(relPath));
    if (r.status < 200 || r.status >= 300) {
      throw new Error(`GET ${relPath} failed: HTTP ${r.status}`);
    }
    return r.body;
  }
  /** 计算断点续传 Range（默认从头；offset 指定已下载字节数） */
  async getFileRange(relPath, offset) {
    const r = await this.request("GET", this.url(relPath), {
      headers: { Range: `bytes=${offset}-` }
    });
    if (r.status < 200 || r.status >= 300 && r.status !== 206) {
      throw new Error(`GET(range) ${relPath} failed: HTTP ${r.status}`);
    }
    return r.body;
  }
  /** 创建目录 */
  async mkdir(relPath) {
    const r = await this.request("MKCOL", this.url(relPath));
    if (r.status !== 201 && r.status !== 405) {
      throw new Error(`MKCOL ${relPath} failed: HTTP ${r.status}`);
    }
  }
  /** 上传文件（小文件整 PUT，大文件 chunking v2；大文件失败回退整 PUT） */
  async putFile(relPath, data, contentType) {
    const threshold = this.settings.largeFileThresholdMb * 1024 * 1024;
    const caps = await this.getCapsCached();
    if (data.byteLength > threshold && caps.chunkingV2) {
      try {
        await uploadWithChunking(this, relPath, data, this.settings.chunkSizeMb * 1024 * 1024);
        return;
      } catch (e) {
        console.warn(`[nextcloud-sync] chunking failed, fallback to PUT`, e);
      }
    }
    const r = await this.request("PUT", this.url(relPath), {
      body: data,
      contentType: contentType || "application/octet-stream",
      headers: { "If-None-Match": "*" }
    });
    if (r.status < 200 || r.status >= 300) {
      throw new Error(`PUT ${relPath} failed: HTTP ${r.status}`);
    }
  }
  /** 移动/重命名 */
  async move(from, to) {
    const dest = this.url(to);
    const r = await this.request("MOVE", this.url(from), {
      headers: { Destination: dest, Overwrite: "T" }
    });
    if (r.status < 200 || r.status >= 300) {
      throw new Error(`MOVE ${from} -> ${to} failed: HTTP ${r.status}`);
    }
  }
  /** 删除（Nextcloud 默认进回收站） */
  async delete(relPath) {
    const r = await this.request("DELETE", this.url(relPath));
    if (r.status < 200 || r.status >= 300) {
      throw new Error(`DELETE ${relPath} failed: HTTP ${r.status}`);
    }
  }
  /** 是否存在 */
  async exists(relPath) {
    const r = await this.request("PROPFIND", this.url(relPath), {
      headers: { Depth: "0" }
    });
    return r.status >= 200 && r.status < 300;
  }
  /** 单个文件的相关 URL（供 chunkedUpload 复用） */
  get uploadChunkUrl() {
    return (p, forUpload = true) => this.url(p, forUpload);
  }
  /** 暴露底层 request 给 chunkedUpload 使用 */
  rawRequest(method, url, opts) {
    return this.request(method, url, opts);
  }
};

// src/sync/stateStore.ts
var StateStore = class {
  constructor(adapter, filePath) {
    this.states = /* @__PURE__ */ new Map();
    this.dirty = false;
    this.adapter = adapter;
    this.filePath = filePath;
  }
  async load() {
    try {
      if (await this.adapter.exists(this.filePath)) {
        const raw = await this.adapter.read(this.filePath);
        const obj = JSON.parse(raw || "{}");
        this.states = new Map(Object.entries(obj));
      }
    } catch {
      this.states = /* @__PURE__ */ new Map();
    }
  }
  async save() {
    if (!this.dirty)
      return;
    const obj = Object.fromEntries(this.states);
    await this.adapter.write(this.filePath, JSON.stringify(obj, null, 0));
    this.dirty = false;
  }
  get(path) {
    return this.states.get(path);
  }
  /** 记录一次成功同步后的状态 */
  set(path, size, mtime, etag) {
    this.states.set(path, { path, size, mtime, etag });
    this.dirty = true;
  }
  remove(path) {
    if (this.states.delete(path))
      this.dirty = true;
  }
  clear() {
    this.states.clear();
    this.dirty = true;
  }
  keys() {
    return Array.from(this.states.keys());
  }
};

// src/sync/engine.ts
var import_obsidian3 = require("obsidian");

// src/sync/conflictResolver.ts
var ConflictResolver = class {
  /** 生成形如 `dir/name.sync-conflict-20260817-221500.md` 的路径 */
  static makeConflictPath(originalPath, date = /* @__PURE__ */ new Date()) {
    const idx = originalPath.lastIndexOf("/");
    const dir = idx >= 0 ? originalPath.slice(0, idx + 1) : "";
    const base = idx >= 0 ? originalPath.slice(idx + 1) : originalPath;
    const dot = base.lastIndexOf(".");
    const name = dot > 0 ? base.slice(0, dot) : base;
    const ext = dot > 0 ? base.slice(dot) : "";
    const stamp = `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, "0")}${String(date.getDate()).padStart(2, "0")}-${String(date.getHours()).padStart(2, "0")}${String(date.getMinutes()).padStart(2, "0")}${String(date.getSeconds()).padStart(2, "0")}`;
    return `${dir}${name}.sync-conflict-${stamp}${ext}`;
  }
};

// src/sync/engine.ts
function simpleGlobToRegExp(glob) {
  if (!glob)
    return null;
  let re = "";
  for (const ch of glob) {
    if (ch === "*")
      re += "[^/]*";
    else if (ch === "?")
      re += "[^/]";
    else
      re += ch.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  }
  try {
    return new RegExp(`^${re}$`);
  } catch {
    return null;
  }
}
var SyncEngine = class {
  constructor(deps) {
    this.deps = deps;
  }
  /** 忽略判断：点开头/隐藏、.obsidian、excludePatterns、冲突文件 */
  shouldExclude(path) {
    const segments = path.split("/").filter(Boolean);
    for (const seg of segments) {
      if (seg.startsWith("."))
        return true;
    }
    if (path.includes(".sync-conflict-"))
      return true;
    const patterns = this.deps.settings.excludePatterns.split(/\r?\n/).map((p) => p.trim()).filter(Boolean);
    for (const p of patterns) {
      const re = simpleGlobToRegExp(p);
      if (re && re.test(path))
        return true;
    }
    return false;
  }
  /** 本地文件枚举（vault 内存模型，已过滤忽略项） */
  async collectLocalFiles() {
    const files = this.deps.vault.getFiles();
    const out = [];
    for (const f of files) {
      if (this.shouldExclude(f.path))
        continue;
      out.push({ path: f.path, size: f.stat.size, mtime: f.stat.mtime });
    }
    return out;
  }
  /** 计算 diff（智能模式四象限） */
  computeDiff(local, remote, mode) {
    const localMap = new Map(local.map((f) => [f.path, f]));
    const remoteMap = new Map(
      remote.filter((r) => !r.isDir).map((r) => [r.path, r])
    );
    const state = this.deps.state;
    const plan = {
      toUpload: [],
      toDownload: [],
      toDeleteLocal: [],
      toDelete: [],
      conflicts: []
    };
    if (mode === "force-push") {
      for (const f of local)
        plan.toUpload.push(f.path);
      for (const r of remoteMap.keys()) {
        if (!localMap.has(r))
          plan.toDelete.push(r);
      }
      return plan;
    }
    if (mode === "force-pull") {
      for (const r of remoteMap.keys())
        plan.toDownload.push(r);
      for (const f of localMap.keys()) {
        if (!remoteMap.has(f))
          plan.toDeleteLocal.push(f);
      }
      return plan;
    }
    const allPaths = /* @__PURE__ */ new Set([...localMap.keys(), ...remoteMap.keys()]);
    for (const path of allPaths) {
      const l = localMap.get(path);
      const r = remoteMap.get(path);
      const s = state.get(path);
      if (l && r) {
        const localChanged = !s || s.size !== l.size || s.mtime !== l.mtime;
        const remoteChanged = !s || s.etag !== r.etag;
        if (localChanged && !remoteChanged)
          plan.toUpload.push(path);
        else if (!localChanged && remoteChanged)
          plan.toDownload.push(path);
        else if (localChanged && remoteChanged)
          plan.conflicts.push(path);
      } else if (l && !r) {
        plan.toUpload.push(path);
      } else if (!l && r) {
        plan.toDownload.push(path);
      }
    }
    return plan;
  }
  /** 执行计划 */
  async execute(plan) {
    const { vault, client, state, settings } = this.deps;
    const result = {
      uploaded: 0,
      downloaded: 0,
      deletedLocal: 0,
      deletedRemote: 0,
      conflicts: 0,
      skipped: 0,
      errors: 0
    };
    const total = plan.toUpload.length + plan.toDownload.length + plan.toDelete.length + plan.toDeleteLocal.length + plan.conflicts.length;
    let done = 0;
    const tick = (label) => {
      done++;
      this.deps.onProgress?.(done, total, label);
    };
    for (const path of plan.toUpload) {
      try {
        const f = vault.getAbstractFileByPath(path);
        if (!(f instanceof import_obsidian3.TFile))
          continue;
        const data = await vault.adapter.readBinary(path);
        await client.putFile(path, data, "application/octet-stream");
        const lf = vault.getFileByPath(path);
        state.set(path, lf?.stat.size ?? f.stat.size, lf?.stat.mtime ?? f.stat.mtime);
        result.uploaded++;
      } catch (e) {
        result.errors++;
        console.error(`[nextcloud-sync] upload ${path} failed`, e);
      }
      tick(`\u4E0A\u4F20 ${path}`);
    }
    for (const path of plan.toDownload) {
      try {
        const data = await client.getFile(path);
        await this.ensureLocalParent(path);
        await vault.adapter.writeBinary(path, data);
        const lf = vault.getFileByPath(path);
        state.set(path, lf?.stat.size ?? data.byteLength, lf?.stat.mtime ?? Date.now());
        result.downloaded++;
      } catch (e) {
        result.errors++;
        console.error(`[nextcloud-sync] download ${path} failed`, e);
      }
      tick(`\u4E0B\u8F7D ${path}`);
    }
    for (const path of plan.conflicts) {
      try {
        const data = await client.getFile(path);
        const conflictPath = ConflictResolver.makeConflictPath(path);
        await this.ensureLocalParent(conflictPath);
        await vault.adapter.writeBinary(conflictPath, data);
        const f = vault.getAbstractFileByPath(path);
        if (f instanceof import_obsidian3.TFile) {
          const localData = await vault.adapter.readBinary(path);
          await client.putFile(path, localData, "application/octet-stream");
          const lf = vault.getFileByPath(path);
          state.set(path, lf?.stat.size ?? f.stat.size, lf?.stat.mtime ?? f.stat.mtime);
        }
        result.conflicts++;
      } catch (e) {
        result.errors++;
        console.error(`[nextcloud-sync] conflict ${path} failed`, e);
      }
      tick(`\u51B2\u7A81 ${path}`);
    }
    for (const path of plan.toDelete) {
      if (settings.deleteStrategy === "never")
        continue;
      try {
        await client.delete(path);
        state.remove(path);
        result.deletedRemote++;
      } catch (e) {
        result.errors++;
        console.error(`[nextcloud-sync] delete-remote ${path} failed`, e);
      }
      tick(`\u5220\u9664\u8FDC\u7AEF ${path}`);
    }
    for (const path of plan.toDeleteLocal) {
      if (settings.deleteStrategy === "never")
        continue;
      try {
        const af = vault.getAbstractFileByPath(path);
        if (af)
          await vault.trash(af, false);
        state.remove(path);
        result.deletedLocal++;
      } catch (e) {
        result.errors++;
        console.error(`[nextcloud-sync] delete-local ${path} failed`, e);
      }
      tick(`\u5220\u9664\u672C\u5730 ${path}`);
    }
    await state.save();
    return result;
  }
  /** 确保本地父目录存在 */
  async ensureLocalParent(path) {
    const idx = path.lastIndexOf("/");
    if (idx < 0)
      return;
    const dir = path.slice(0, idx);
    if (!await this.deps.vault.adapter.exists(dir)) {
      await this.deps.vault.adapter.mkdir(dir);
    }
  }
  /** 仅计算计划（用于强制操作前的二次确认统计） */
  async preview(mode) {
    const local = await this.collectLocalFiles();
    const remote = await this.deps.client.listAll();
    return this.computeDiff(local, remote, mode);
  }
  /** 顶层编排 */
  async sync(mode) {
    const local = await this.collectLocalFiles();
    const remote = await this.deps.client.listAll();
    const plan = this.computeDiff(local, remote, mode);
    const result = await this.execute(plan);
    const summary = `\u4E0A\u4F20${result.uploaded} \u4E0B\u8F7D${result.downloaded} \u8DF3\u8FC7${result.skipped} \u51B2\u7A81${result.conflicts}`;
    if (result.errors > 0) {
      new import_obsidian3.Notice(`Nextcloud \u540C\u6B65\u5B8C\u6210\uFF08\u6709\u9519\u8BEF\uFF09\uFF1A${summary} \u9519\u8BEF${result.errors}`);
    } else {
      new import_obsidian3.Notice(`Nextcloud \u540C\u6B65\u5B8C\u6210\uFF1A${summary}`);
    }
    return result;
  }
};

// src/logger/logger.ts
var Logger = class {
  constructor() {
    this.listeners = [];
    this.buffer = [];
    this.maxBuffer = 2e3;
  }
  subscribe(fn) {
    this.listeners.push(fn);
  }
  unsubscribe(fn) {
    this.listeners = this.listeners.filter((l) => l !== fn);
  }
  log(level, action, path, detail, sizeBytes, durationMs) {
    const entry = {
      timestamp: Date.now(),
      level,
      action,
      path,
      detail,
      sizeBytes,
      durationMs
    };
    this.buffer.push(entry);
    if (this.buffer.length > this.maxBuffer)
      this.buffer.shift();
    for (const l of this.listeners) {
      try {
        l(entry);
      } catch {
      }
    }
  }
  getBuffer() {
    return this.buffer.slice();
  }
  clear() {
    this.buffer = [];
  }
};

// src/logger/logStore.ts
var LogStore = class {
  constructor(adapter, dir, retentionDays) {
    this.today = "";
    this.path = "";
    this.adapter = adapter;
    this.dir = dir.replace(/\/+$/, "");
    this.retentionDays = retentionDays;
  }
  /** 订阅 logger，并立即清理过期文件 */
  attach(logger) {
    logger.subscribe((e) => this.append(e));
    this.cleanupOld();
  }
  dayStr(d = /* @__PURE__ */ new Date()) {
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  }
  resolvePath() {
    const day = this.dayStr();
    if (day !== this.today) {
      this.today = day;
      this.path = `${this.dir}/sync-${day}.log`;
    }
    return this.path;
  }
  async append(e) {
    try {
      const line = JSON.stringify(e) + "\n";
      const p = this.resolvePath();
      const existing = await this.adapter.exists(p) ? await this.adapter.read(p) : "";
      await this.adapter.write(p, existing + line);
    } catch {
    }
  }
  /** 删除超过保留天数的日志 */
  async cleanupOld() {
    try {
      if (!await this.adapter.exists(this.dir))
        return;
      const listed = await this.adapter.list(this.dir);
      const all = [...listed.files || [], ...listed.folders || []];
      const limit = Date.now() - this.retentionDays * 864e5;
      for (const f of all) {
        if (!f.includes("/sync-") || !f.endsWith(".log"))
          continue;
        const day = f.match(/sync-(\d{4}-\d{2}-\d{2})\.log/);
        if (day) {
          const t = (/* @__PURE__ */ new Date(day[1] + "T00:00:00")).getTime();
          if (t < limit)
            await this.adapter.remove(f);
        }
      }
    } catch {
    }
  }
};

// src/logger/logView.ts
var import_obsidian4 = require("obsidian");
var LOG_VIEW_TYPE = "nextcloud-sync-log-view";
var SyncLogView = class extends import_obsidian4.ItemView {
  constructor(leaf, logger) {
    super(leaf);
    this.filterLevel = "all";
    this.filterAction = "all";
    this.searchText = "";
    this.logger = logger;
  }
  getViewType() {
    return LOG_VIEW_TYPE;
  }
  getDisplayText() {
    return "Nextcloud Sync";
  }
  getIcon() {
    return "sync";
  }
  async onOpen() {
    const root = this.containerEl.children[1];
    root.empty();
    this.rootEl = root;
    this.renderControls();
    this.renderList();
    this.logger.subscribe(() => this.renderList());
  }
  async onClose() {
  }
  renderControls() {
    const wrap = this.rootEl.createDiv({ cls: "nc-log-controls" });
    const levelSel = wrap.createEl("select");
    ["all", "info", "warn", "error", "debug"].forEach((l) => {
      const o = levelSel.createEl("option", { text: l, value: l });
      if (l === this.filterLevel)
        o.selected = true;
    });
    levelSel.onchange = () => {
      this.filterLevel = levelSel.value;
      this.renderList();
    };
    const actionSel = wrap.createEl("select");
    ["all", "upload", "download", "delete-local", "delete-remote", "skip", "conflict", "error"].forEach(
      (a) => {
        const o = actionSel.createEl("option", { text: a, value: a });
        if (a === this.filterAction)
          o.selected = true;
      }
    );
    actionSel.onchange = () => {
      this.filterAction = actionSel.value;
      this.renderList();
    };
    const search = wrap.createEl("input", { placeholder: "\u641C\u7D22\u6587\u4EF6\u540D" });
    search.oninput = () => {
      this.searchText = search.value.toLowerCase();
      this.renderList();
    };
  }
  renderList() {
    const listEl = this.rootEl.querySelector(".nc-log-list");
    const target = listEl ?? this.rootEl.createDiv({ cls: "nc-log-list" });
    target.empty();
    const entries = this.logger.getBuffer().filter((e) => {
      if (this.filterLevel !== "all" && e.level !== this.filterLevel)
        return false;
      if (this.filterAction !== "all" && e.action !== this.filterAction)
        return false;
      if (this.searchText && !e.path.toLowerCase().includes(this.searchText))
        return false;
      return true;
    });
    for (const e of entries) {
      const row = target.createDiv({ cls: `nextcloud-sync-log-entry nc-level-${e.level}` });
      row.createSpan({ cls: "nc-log-level", text: e.level });
      row.createSpan({ cls: "nc-log-action", text: e.action });
      const pathEl = row.createSpan({ cls: "nc-log-path", text: e.path });
      if (e.detail)
        row.setAttribute("title", e.detail);
      pathEl.onClickEvent(() => {
        if (e.path && e.action !== "delete-remote") {
          const file = this.app.vault.getAbstractFileByPath(e.path);
          if (file)
            this.app.workspace.getLeaf(false).openFile(file);
        }
      });
    }
  }
};

// src/ui/statusBar.ts
var import_obsidian5 = require("obsidian");
var StatusBar = class {
  constructor(el) {
    this.el = el;
    this.el.addClass("nc-status-bar");
    this.setIdle();
  }
  setIdle() {
    this.el.setText("Nextcloud: \u7A7A\u95F2");
    (0, import_obsidian5.setIcon)(this.el, "cloud");
    (0, import_obsidian5.setTooltip)(this.el, "Nextcloud Sync \u7A7A\u95F2");
  }
  setSyncing(done, total, label) {
    this.el.setText(`Nextcloud: \u540C\u6B65\u4E2D ${done}/${total} ${label}`);
    (0, import_obsidian5.setIcon)(this.el, "refresh-cw");
  }
  setResult(r) {
    const ok = r.errors === 0;
    const text = `Nextcloud: \u2714 \u4E0A\u4F20${r.uploaded} \u4E0B\u8F7D${r.downloaded} \u51B2\u7A81${r.conflicts}${r.errors ? ` \u9519\u8BEF${r.errors}` : ""}`;
    this.el.setText(text);
    (0, import_obsidian5.setIcon)(this.el, ok ? "check" : "alert-triangle");
    (0, import_obsidian5.setTooltip)(this.el, text);
  }
};

// src/ui/confirmModal.ts
var import_obsidian6 = require("obsidian");
var ConfirmModal = class extends import_obsidian6.Modal {
  constructor(app, mode, plan, onConfirm) {
    super(app);
    this.mode = mode;
    this.plan = plan;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    const title = this.mode === "force-push" ? "\u5F3A\u5236\u4E0A\u4F20" : "\u5F3A\u5236\u4E0B\u8F7D";
    contentEl.createEl("h3", { text: `${title}\u786E\u8BA4` });
    contentEl.createEl("p", {
      text: this.mode === "force-push" ? "\u5C06\u7528\u672C\u5730\u8986\u76D6\u8FDC\u7AEF\u3002\u8FDC\u7AEF\u591A\u4F59\u6587\u4EF6\u5C06\u8FDB\u5165 Nextcloud \u56DE\u6536\u7AD9\uFF08\u53EF\u5728\u7F51\u9875\u7AEF\u6062\u590D\uFF09\u3002" : "\u5C06\u7528\u8FDC\u7AEF\u8986\u76D6\u672C\u5730\u3002\u672C\u5730\u591A\u4F59\u6587\u4EF6\u5C06\u8FDB\u5165\u7CFB\u7EDF\u56DE\u6536\u7AD9\u3002"
    });
    const counts = contentEl.createDiv();
    counts.createEl("div", { text: `\u4E0A\u4F20/\u8986\u76D6\uFF1A${this.plan.toUpload.length}` });
    counts.createEl("div", { text: `\u4E0B\u8F7D/\u8986\u76D6\uFF1A${this.plan.toDownload.length}` });
    counts.createEl("div", { text: `\u5220\u9664\u8FDC\u7AEF\uFF1A${this.plan.toDelete.length}` });
    counts.createEl("div", { text: `\u5220\u9664\u672C\u5730\uFF1A${this.plan.toDeleteLocal.length}` });
    new import_obsidian6.Setting(contentEl).addButton(
      (b) => b.setButtonText("\u786E\u8BA4\u6267\u884C").setCta().onClick(() => {
        this.close();
        this.onConfirm();
      })
    ).addButton((b) => b.setButtonText("\u53D6\u6D88").onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var NextcloudSyncPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.logger = new Logger();
    this.running = false;
  }
  async onload() {
    await this.loadSettings();
    const pluginDir = `${this.app.vault.configDir}/plugins/nextcloud-sync`;
    this.stateStore = new StateStore(this.app.vault.adapter, `${pluginDir}/sync-state.json`);
    await this.stateStore.load();
    this.logStore = new LogStore(this.app.vault.adapter, `${pluginDir}/logs`, this.settings.logRetentionDays);
    this.logStore.attach(this.logger);
    this.statusBar = new StatusBar(this.addStatusBarItem());
    this.registerView(LOG_VIEW_TYPE, (leaf) => new SyncLogView(leaf, this.logger));
    this.addCommand({ id: "sync", name: "Sync", callback: () => this.doSync("smart") });
    this.addCommand({ id: "force-push", name: "Force push (\u672C\u5730\u8986\u76D6\u8FDC\u7AEF)", callback: () => this.requestForce("force-push") });
    this.addCommand({ id: "force-pull", name: "Force pull (\u8FDC\u7AEF\u8986\u76D6\u672C\u5730)", callback: () => this.requestForce("force-pull") });
    this.addCommand({ id: "open-log", name: "\u6253\u5F00\u540C\u6B65\u65E5\u5FD7", callback: () => this.activateLogView() });
    this.addCommand({ id: "test-conn", name: "\u6D4B\u8BD5\u8FDE\u63A5", callback: async () => {
      const ok = await this.testConnection();
      new import_obsidian7.Notice(ok ? "\u2705 \u8FDE\u63A5\u6210\u529F" : "\u274C \u8FDE\u63A5\u5931\u8D25");
    } });
    this.addRibbonIcon("sync", "Nextcloud Sync", () => this.doSync("smart"));
    this.addSettingTab(new NextcloudSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.syncOnStartup)
        this.doSync("smart");
    });
    if (this.settings.syncOnChange)
      this.registerChangeWatcher();
    if (this.settings.autoSyncIntervalMinutes > 0) {
      const ms = this.settings.autoSyncIntervalMinutes * 6e4;
      const id = window.setInterval(() => this.doSync("smart"), ms);
      this.registerInterval(id);
    }
  }
  onunload() {
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...data || {} };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  buildClient() {
    return new WebdavClient(this.settings);
  }
  async testConnection() {
    try {
      return await this.buildClient().testConnection();
    } catch {
      return false;
    }
  }
  buildEngine() {
    return new SyncEngine({
      vault: this.app.vault,
      settings: this.settings,
      client: this.buildClient(),
      state: this.stateStore,
      onProgress: (done, total, label) => this.statusBar.setSyncing(done, total, label)
    });
  }
  async doSync(mode) {
    if (this.running) {
      new import_obsidian7.Notice("\u540C\u6B65\u6B63\u5728\u8FDB\u884C\u4E2D\uFF0C\u5DF2\u8DF3\u8FC7\u672C\u6B21\u89E6\u53D1");
      return;
    }
    if (!this.settings.serverUrl || !this.settings.username || !this.settings.appPassword) {
      new import_obsidian7.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 Nextcloud \u8FDE\u63A5\u4FE1\u606F");
      return;
    }
    this.running = true;
    this.statusBar.setSyncing(0, 0, mode);
    try {
      const result = await this.buildEngine().sync(mode);
      this.statusBar.setResult(result);
    } catch (e) {
      console.error("[nextcloud-sync]", e);
      new import_obsidian7.Notice("\u540C\u6B65\u51FA\u9519\uFF0C\u8BE6\u89C1\u63A7\u5236\u53F0");
      this.statusBar.setIdle();
    } finally {
      this.running = false;
    }
  }
  /** 强制操作：先计算统计，再弹二次确认 */
  async requestForce(mode) {
    if (this.running) {
      new import_obsidian7.Notice("\u540C\u6B65\u6B63\u5728\u8FDB\u884C\u4E2D\uFF0C\u5DF2\u8DF3\u8FC7\u672C\u6B21\u89E6\u53D1");
      return;
    }
    try {
      const engine = this.buildEngine();
      const plan = await engine.preview(mode);
      new ConfirmModal(this.app, mode, plan, () => this.doSync(mode)).open();
    } catch (e) {
      console.error("[nextcloud-sync]", e);
      new import_obsidian7.Notice("\u51C6\u5907\u5F3A\u5236\u64CD\u4F5C\u5931\u8D25\uFF0C\u8BE6\u89C1\u63A7\u5236\u53F0");
    }
  }
  registerChangeWatcher() {
    const debounced = (0, import_obsidian7.debounce)(() => this.doSync("smart"), this.settings.syncOnChangeDebounceMs, true);
    this.changeHandler = () => debounced();
    this.registerEvent(this.app.vault.on("create", () => this.changeHandler()));
    this.registerEvent(this.app.vault.on("modify", () => this.changeHandler()));
    this.registerEvent(this.app.vault.on("delete", () => this.changeHandler()));
    this.registerEvent(this.app.vault.on("rename", () => this.changeHandler()));
  }
  async activateLogView() {
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: LOG_VIEW_TYPE, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
  }
};
